import { useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";
import { describeAppError } from "./error";
import { takeFocus } from "./focus";
import { useProjectContext } from "./projectContext";
import { StatusNotice, useConfirmation } from "./Feedback";

type Project={id:string;number:string;name:string;projectPath:string};
type FileRecord={id:string;projectId:string;projectNumber:string;projectName:string;fileName:string;filePath:string;operation:string;discipline:string|null;drawingNumber:string|null;title:string|null;revision:string|null;revisionDate:string|null;receivedDate:string|null;isCurrent:boolean;missing:boolean};
const disciplines=["controls","mechanical","electrical","architectural"];

export function Files(){
 const projectContext=useProjectContext();
 const[files,setFiles]=useState<FileRecord[]>([]),[projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<FileRecord|null>(null);
 const[showCreate,setShowCreate]=useState(false);
 const[projectId,setProjectId]=useState(""),[sourcePath,setSourcePath]=useState(""),[operation,setOperation]=useState("register"),[discipline,setDiscipline]=useState(""),[drawingNumber,setDrawingNumber]=useState(""),[title,setTitle]=useState(""),[revision,setRevision]=useState(""),[revisionDate,setRevisionDate]=useState(""),[receivedDate,setReceivedDate]=useState(""),[isCurrent,setIsCurrent]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
 const{confirmAction,confirmationDialog}=useConfirmation();
 useEffect(()=>setProjectId(projectContext),[projectContext]);
 const load=async()=>{try{const[a,b]=await Promise.all([invoke<FileRecord[]>("list_files"),invoke<Project[]>("list_projects",{includeArchived:false})]);setFiles(a);setProjects(b);const id=takeFocus("files");const focused=a.find(v=>v.id===id);if(focused)edit(focused)}catch(e){setError(describeAppError(e))}};useEffect(()=>{void load()},[]);
 useEffect(()=>{const handler=()=>{setShowCreate(true);void choose("Select file").then(value=>value&&setSourcePath(value))};window.addEventListener("workspace:new",handler);return()=>window.removeEventListener("workspace:new",handler)},[]);
 const choose=async(title:string)=>{const value=await open({multiple:false,directory:false,title});return typeof value==="string"?value:null};
 const operationCopy=({register:{heading:"Register an existing file",description:"Keep the file in its current location and add a reference to this register.",action:"Register file"},copy:{heading:"Copy a file into the project",description:"Create a project copy. The original file stays in its current location.",action:"Copy into project"},move:{heading:"Move a file into the project",description:"Move the original file from its current location into the project drawing folder.",action:"Move into project"}} as const)[operation as "register"|"copy"|"move"];
 const destinationPreview=()=>{const project=projects.find(value=>value.id===projectId);if(!project||!sourcePath||operation==="register")return null;const name=sourcePath.split(/[\\/]/).pop()??sourcePath;const folder=({controls:"Controls",mechanical:"Mechanical",electrical:"Electrical",architectural:"Architectural"} as Record<string,string>)[discipline];return `${project.projectPath}\\01 Drawings${folder?`\\${folder}`:""}\\${name}`};
 const edit=(file:FileRecord)=>{setSelected(file);setDiscipline(file.discipline??"");setDrawingNumber(file.drawingNumber??"");setTitle(file.title??"");setRevision(file.revision??"");setRevisionDate(file.revisionDate??"");setReceivedDate(file.receivedDate??"");setIsCurrent(file.isCurrent)};
 const metadata=()=>({discipline:discipline||null,drawingNumber:drawingNumber||null,title:title||null,revision:revision||null,revisionDate:revisionDate||null,receivedDate:receivedDate||null,isCurrent});
 async function saveNew(e:React.FormEvent){e.preventDefault();const destination=destinationPreview();if(operation==="move"&&!await confirmAction({title:"Move this file?",description:<><p><strong>From:</strong> {sourcePath}</p><p><strong>To:</strong> {destination}</p><p>The original will no longer remain at its current location. Existing destinations are never overwritten.</p></>,confirmLabel:"Move file",destructive:true}))return;try{await invoke("create_file",{input:{projectId,sourcePath,operation,...metadata()}});setSourcePath("");setShowCreate(false);setMessage(operation==="register"?"File reference registered.":operation==="copy"?"File copied into the project and registered.":"File moved into the project and registered.");await load()}catch(x){setError(describeAppError(x))}}
 async function saveMetadata(){if(!selected)return;try{const saved=await invoke<FileRecord>("update_file_metadata",{id:selected.id,input:metadata()});setSelected(saved);setMessage("Drawing metadata updated.");await load()}catch(x){setError(describeAppError(x))}}
 async function locate(id:string){const path=await choose("Locate missing file");if(path){try{await invoke("locate_file",{id,path});setMessage("File reference updated.");await load()}catch(x){setError(describeAppError(x))}}}
 async function removeReference(file:FileRecord){if(!await confirmAction({title:"Remove this file reference?",description:<><p><strong>{file.fileName}</strong> will be removed from the register.</p><p>The original file will not be changed or deleted.</p></>,confirmLabel:"Remove reference",destructive:true}))return;try{await invoke("remove_file_reference",{id:file.id});setMessage("File reference removed. The original file was not changed.");await load()}catch(x){setError(describeAppError(x))}}
 const visibleFiles=projectContext?files.filter(file=>file.projectId===projectContext):files;
 return <section className="projects-page" aria-labelledby="files-title">{confirmationDialog}<div className="page-toolbar"><div><p className="eyebrow">Files</p><h1 id="files-title">Drawing and file register</h1></div><button type="button" onClick={()=>setShowCreate(value=>!value)}>{showCreate?"Close register":"Add file"}</button></div>
 {showCreate&&<form className="create-panel" onSubmit={saveNew}><h2>{operationCopy.heading}</h2><p>{operationCopy.description} Existing destinations are never overwritten.</p><div className="form-grid"><label>Project<select required value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Choose project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.number} — {p.name}</option>)}</select></label><label>Operation<select value={operation} onChange={e=>setOperation(e.target.value)}><option value="register">Register only</option><option value="copy">Copy into project</option><option value="move">Move into project</option></select></label><label className="wide-field">Source file<div className="path-control"><input readOnly required value={sourcePath}/><button type="button" className="secondary" onClick={()=>void choose("Select file").then(v=>v&&setSourcePath(v))}>Choose file…</button></div></label></div><details className="optional-details"><summary>Drawing metadata</summary><div className="form-grid"><label>Discipline<select value={discipline} onChange={e=>setDiscipline(e.target.value)}><option value="">General</option>{disciplines.map(v=><option key={v}>{v}</option>)}</select></label><label>Drawing number<input value={drawingNumber} onChange={e=>setDrawingNumber(e.target.value)}/></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Revision<input value={revision} onChange={e=>setRevision(e.target.value)}/></label><label>Revision date<input type="date" value={revisionDate} onChange={e=>setRevisionDate(e.target.value)}/></label><label>Received date<input type="date" value={receivedDate} onChange={e=>setReceivedDate(e.target.value)}/></label></div></details>{sourcePath&&<dl className={`operation-preview operation-${operation}`}><div><dt>Source</dt><dd>{sourcePath}</dd></div>{destinationPreview()&&<div><dt>{operation==="move"?"New location":"Project copy"}</dt><dd>{destinationPreview()}</dd></div>}</dl>}<div className="actions"><button className={operation==="move"?"destructive":undefined} disabled={!projectId||!sourcePath}>{operationCopy.action}</button><button type="button" className="secondary" onClick={()=>setShowCreate(false)}>Cancel</button></div></form>}
 {message&&<StatusNotice tone="success">{message}</StatusNotice>}{error&&<StatusNotice tone="error">{error}</StatusNotice>}<div className={`rfi-layout${selected?" has-detail":" register-only"}`}><div className="table-scroll"><table><thead><tr><th>Drawing / file</th><th>Project</th><th>Revision</th><th>State</th><th>Actions</th></tr></thead><tbody>{visibleFiles.map(f=><tr key={f.id} className={selected?.id===f.id?"selected-row":""} aria-selected={selected?.id===f.id}><td><button className="project-link" onClick={()=>edit(f)}><strong>{f.drawingNumber??f.fileName}</strong><span className="task-subline">{f.title??f.fileName}</span></button></td><td>{f.projectNumber} — {f.projectName}</td><td>{f.revision??"—"}</td><td>{f.missing?"Missing":f.isCurrent?"Current":"Superseded"}</td><td className="row-actions">{f.missing?<button className="quiet" onClick={()=>void locate(f.id)}>Locate</button>:<button className="quiet" onClick={()=>void invoke("show_file_in_explorer",{id:f.id})}>Explorer</button>}<button className="quiet" onClick={()=>void removeReference(f)}>Remove reference</button></td></tr>)}</tbody></table></div>
 {selected&&<aside className="rfi-detail"><div className="detail-heading"><h2>Edit drawing metadata</h2><button className="quiet" onClick={()=>setSelected(null)}>Close</button></div><div className="detail-form form-grid"><label>Discipline<select value={discipline} onChange={e=>setDiscipline(e.target.value)}><option value="">General</option>{disciplines.map(v=><option key={v}>{v}</option>)}</select></label><label>Drawing number<input value={drawingNumber} onChange={e=>setDrawingNumber(e.target.value)}/></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Revision<input value={revision} onChange={e=>setRevision(e.target.value)}/></label><label>Revision date<input type="date" value={revisionDate} onChange={e=>setRevisionDate(e.target.value)}/></label><label>Received date<input type="date" value={receivedDate} onChange={e=>setReceivedDate(e.target.value)}/></label><label className="checkbox-field"><input type="checkbox" checked={isCurrent} onChange={e=>setIsCurrent(e.target.checked)}/> Current revision</label></div><button onClick={()=>void saveMetadata()}>Save metadata</button></aside>}</div></section>;
}
