import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { describeAppError } from "./error";
import { summarizeProjectAttention } from "./overviewData";
import { useProjectContext } from "./projectContext";
import { LoadingState } from "./Feedback";

type Project = { id:string; number:string; name:string; status:string; phase:string; customPhaseName:string|null };
type Task = { id:string; projectId:string; projectNumber:string; projectName:string; title:string; status:string; priority:string; dueDate:string|null; followUpDate:string|null; waitingOn:string|null };
type AttentionSection = { key:string; label:string; tasks:Task[] };
type RfiAttention = { id:string; projectId:string; projectNumber:string; projectName:string; number:string; subject:string; recipient:string|null; responseDueDate:string|null; status:string };
type SubmittalAttention = { id:string; projectId:string; projectNumber:string; projectName:string; number:string; name:string; recipient:string|null; submittedDate:string|null; status:string };
type WorkItem = { id:string; projectId:string; projectNumber:string; projectName:string; itemType:string; title:string; status:string; dueDate:string|null };
type Note = { id:string; projectId:string|null; projectNumber:string|null; projectName:string|null; body:string; createdAtUtc:string };
type Activity = { eventType:string; entityType:string; summary:string; occurredAtUtc:string };

const label=(value:string)=>value.replace(/_/g," ").replace(/\b\w/g,(letter:string)=>letter.toUpperCase());
const localDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const dateWindow=()=>{const today=new Date();const through=new Date(today.getFullYear(),today.getMonth(),today.getDate()+14);return{today:localDate(today),through:localDate(through)}};
const formatDate=(value:string|null)=>value?new Date(`${value}T00:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"}):"No date";

export function Overview({onNavigate,onSelectProject}:{onNavigate:(screen:string)=>void;onSelectProject:(projectId:string)=>void}){
  const context=useProjectContext();
  const [projects,setProjects]=useState<Project[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [sections,setSections]=useState<AttentionSection[]>([]);const [rfis,setRfis]=useState<RfiAttention[]>([]);const [submittals,setSubmittals]=useState<SubmittalAttention[]>([]);const [workItems,setWorkItems]=useState<WorkItem[]>([]);const [notes,setNotes]=useState<Note[]>([]);const [activity,setActivity]=useState<Activity[]>([]);
  const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{const range=dateWindow();setLoading(true);void Promise.all([invoke<Project[]>("list_projects",{includeArchived:false}),invoke<Task[]>("list_tasks"),invoke<AttentionSection[]>("list_attention",range),invoke<RfiAttention[]>("list_rfi_attention",range),invoke<SubmittalAttention[]>("list_submittal_attention"),invoke<WorkItem[]>("list_work_items"),invoke<Note[]>("list_notes"),invoke<Activity[]>("list_activity")]).then(([p,t,a,r,s,w,n,h])=>{setProjects(p);setTasks(t);setSections(a);setRfis(r);setSubmittals(s);setWorkItems(w);setNotes(n);setActivity(h);setError("")}).catch((caught)=>setError(describeAppError(caught))).finally(()=>setLoading(false))},[]);
  const scope=<T extends {projectId:string}>(items:T[])=>context?items.filter((item)=>item.projectId===context):items;
  const scopedSections=useMemo(()=>sections.map((section)=>({...section,tasks:scope(section.tasks)})),[sections,context]);
  const scopedRfis=useMemo(()=>scope(rfis),[rfis,context]);const scopedSubmittals=useMemo(()=>scope(submittals),[submittals,context]);
  const immediate=useMemo(()=>scopedSections.filter((section)=>section.key!=="upcoming").flatMap((section)=>section.tasks.map((task)=>({...task,reason:section.label}))),[scopedSections]);
  const upcoming=useMemo(()=>scopedSections.find((section)=>section.key==="upcoming")?.tasks??[],[scopedSections]);
  const milestones=useMemo(()=>scope(workItems).filter((item)=>item.itemType==="milestone"&&!["completed","cancelled"].includes(item.status)).sort((a,b)=>(a.dueDate??"9999").localeCompare(b.dueDate??"9999")),[workItems,context]);
  const scopedNotes=useMemo(()=>notes.filter((note)=>context?note.projectId===context:Boolean(note.projectId)),[notes,context]);
  const projectAttention=useMemo(()=>summarizeProjectAttention(immediate,rfis,submittals),[immediate,rfis,submittals]);
  const selected=projects.find((project)=>project.id===context);const scopeName=selected?`${selected.number} — ${selected.name}`:"All active projects";
  const activeTasks=scope(tasks).filter((task)=>!["completed","cancelled"].includes(task.status)).length;
  if(loading)return <section className="projects-page"><LoadingState>Loading project overview…</LoadingState></section>;
  return <section className="projects-page overview-page" aria-labelledby="overview-title">
    <div className="page-toolbar"><div><p className="eyebrow">Home</p><h1 id="overview-title">{scopeName}</h1><p className="page-context">{selected?`${label(selected.status)} · ${selected.phase==="custom"?selected.customPhaseName:label(selected.phase)}`:"Priorities, responses, milestones, and recent work across the portfolio."}</p></div></div>
    {error&&<p className="status error" role="alert">{error}</p>}
    <div className="overview-summary" aria-label="Workload summary"><button type="button" onClick={()=>onNavigate("tasks")}><strong>{activeTasks}</strong><span>Active tasks</span></button><button type="button" onClick={()=>onNavigate("attention")}><strong>{immediate.length}</strong><span>Need attention</span></button><button type="button" onClick={()=>onNavigate("rfis")}><strong>{scopedRfis.length}</strong><span>RFI responses</span></button><button type="button" onClick={()=>onNavigate("submittals")}><strong>{scopedSubmittals.length}</strong><span>Submittal reviews</span></button></div>
    <div className="overview-columns">
      <section className="overview-register"><div className="detail-heading"><h2>Immediate work</h2><button type="button" className="quiet" onClick={()=>onNavigate("attention")}>Open Attention</button></div>{immediate.length?<table><thead><tr><th>Task</th><th>Project</th><th>Reason</th><th>Date</th></tr></thead><tbody>{immediate.slice(0,10).map((task)=><tr key={`${task.reason}-${task.id}`}><td>{task.title}</td><td>{task.projectNumber}</td><td>{task.reason}</td><td title={task.dueDate??task.followUpDate??undefined}>{formatDate(task.dueDate??task.followUpDate)}</td></tr>)}</tbody></table>:<p className="empty-state">No overdue, due-today, follow-up, or waiting tasks in this context.</p>}</section>
      <section className="overview-register"><div className="detail-heading"><h2>Awaiting response</h2><div className="actions"><button type="button" className="quiet" onClick={()=>onNavigate("rfis")}>RFIs</button><button type="button" className="quiet" onClick={()=>onNavigate("submittals")}>Submittals</button></div></div>{scopedRfis.length||scopedSubmittals.length?<ul className="overview-list">{scopedRfis.slice(0,5).map((rfi)=><li key={rfi.id}><strong>{rfi.number} — {rfi.subject}</strong><span>{rfi.projectNumber} · RFI{rfi.responseDueDate?` · Due ${formatDate(rfi.responseDueDate)}`:""}</span></li>)}{scopedSubmittals.slice(0,5).map((item)=><li key={item.id}><strong>{item.number} — {item.name}</strong><span>{item.projectNumber} · Submittal · {label(item.status)}</span></li>)}</ul>:<p className="empty-state">No RFIs or submittals are awaiting action.</p>}</section>
      {!context&&<section className="overview-register overview-project-attention"><div className="detail-heading"><h2>Projects needing attention</h2><button type="button" className="quiet" onClick={()=>onNavigate("projects")}>All projects</button></div>{projectAttention.length?<table><thead><tr><th>Project</th><th>Tasks</th><th>RFIs</th><th>Submittals</th><th></th></tr></thead><tbody>{projectAttention.slice(0,10).map((project)=><tr key={project.projectId}><td><strong>{project.projectNumber}</strong> — {project.projectName}</td><td>{project.tasks}</td><td>{project.rfis}</td><td>{project.submittals}</td><td><button type="button" className="table-action" onClick={()=>onSelectProject(project.projectId)}>Open</button></td></tr>)}</tbody></table>:<p className="empty-state">No projects currently require attention.</p>}</section>}
      <section className="overview-register"><div className="detail-heading"><h2>Upcoming</h2><button type="button" className="quiet" onClick={()=>onNavigate("operations")}>Milestones</button></div>{upcoming.length||milestones.length?<ul className="overview-list">{upcoming.slice(0,4).map((task)=><li key={`task-${task.id}`}><strong>{task.title}</strong><span>{task.projectNumber} · Task · {formatDate(task.dueDate)}</span></li>)}{milestones.slice(0,4).map((item)=><li key={`milestone-${item.id}`}><strong>{item.title}</strong><span>{item.projectNumber} · Milestone · {formatDate(item.dueDate)}</span></li>)}</ul>:<p className="empty-state">No tasks or milestones are due in the next 14 days.</p>}</section>
      <section className="overview-register"><div className="detail-heading"><h2>{context?"Recent project notes":"Recent notes"}</h2><button type="button" className="quiet" onClick={()=>onNavigate("notes")}>Open notes</button></div>{scopedNotes.length?<ul className="overview-list">{scopedNotes.slice(0,6).map((note)=><li key={note.id}><strong>{note.body}</strong><span>{!context&&note.projectNumber?`${note.projectNumber} · `:""}{new Date(note.createdAtUtc).toLocaleString()}</span></li>)}</ul>:<p className="empty-state">No notes have been recorded in this context.</p>}</section>
      <section className="overview-register"><div className="detail-heading"><h2>Recent workspace activity</h2><button type="button" className="quiet" onClick={()=>onNavigate("recovery")}>Activity log</button></div>{context&&<p className="section-hint">Activity is workspace-wide; project-specific notes are shown separately.</p>}{activity.length?<ul className="overview-list">{activity.slice(0,6).map((event,index)=><li key={`${event.occurredAtUtc}-${index}`}><strong>{event.summary}</strong><span>{label(event.entityType)} · {new Date(event.occurredAtUtc).toLocaleString()}</span></li>)}</ul>:<p className="empty-state">No workspace activity has been recorded.</p>}</section>
    </div>
  </section>;
}
