import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { describeAppError } from "./error";
import { takeFocus } from "./focus";
import { EmptyState, FieldError, useConfirmation } from "./Feedback";
import { firstFieldError, requiredFieldErrors } from "./formGuidance";

type Project = { id:string; number:string; name:string; status:string; phase:string; customPhaseName:string|null; customer:string|null; generalContractor:string|null; engineer:string|null; projectManager:string|null; superintendent:string|null; location:string|null; startDate:string|null; targetDate:string|null; description:string|null; importantNotes:string|null; projectPath:string; isPinned:boolean; archivedAtUtc:string|null };
type FolderPreview = { projectPath: string };
type Input = { number:string; name:string; status:string; phase:string; customPhaseName:string; customer:string; generalContractor:string; engineer:string; projectManager:string; superintendent:string; location:string; startDate:string; targetDate:string; description:string; importantNotes:string };
const empty = (): Input => ({ number:"",name:"",status:"active",phase:"engineering",customPhaseName:"",customer:"",generalContractor:"",engineer:"",projectManager:"",superintendent:"",location:"",startDate:"",targetDate:"",description:"",importantNotes:"" });
const fromProject = (p:Project):Input => ({ number:p.number,name:p.name,status:p.status,phase:p.phase,customPhaseName:p.customPhaseName??"",customer:p.customer??"",generalContractor:p.generalContractor??"",engineer:p.engineer??"",projectManager:p.projectManager??"",superintendent:p.superintendent??"",location:p.location??"",startDate:p.startDate??"",targetDate:p.targetDate??"",description:p.description??"",importantNotes:p.importantNotes??"" });
const label = (value:string) => ({active:"Active",on_hold:"On Hold",completed:"Completed",cancelled:"Cancelled",preconstruction:"Preconstruction",engineering:"Engineering",submittals:"Submittals",procurement:"Procurement",construction:"Construction",programming:"Programming",startup:"Startup",commissioning:"Commissioning",closeout:"Closeout",custom:"Custom"}[value] ?? value);
type ProjectsProps = { onOpenSettings?:()=>void; onOpenWorkspace?:(project:Project)=>void; onProjectsChanged?:()=>void };
export function Projects({onOpenSettings,onOpenWorkspace,onProjectsChanged}:ProjectsProps={}) {
 const [projects,setProjects]=useState<Project[]>([]); const [form,setForm]=useState<Input>(empty); const [creating,setCreating]=useState(false); const [showForm,setShowForm]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [archived,setArchived]=useState(false); const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState("all"); const [phaseFilter,setPhaseFilter]=useState("all"); const [selected,setSelected]=useState<Project|null>(null); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [formAttempted,setFormAttempted]=useState(false);
 const {confirmAction,confirmationDialog}=useConfirmation();
 const [recentIds,setRecentIds]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem("projects.recent")??"[]") as string[]}catch{return[]}});
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem("projects.filters")??"null");if(v){setArchived(Boolean(v.archived));setSearch(v.search??"");setStatusFilter(v.status??"all");setPhaseFilter(v.phase??"all")}}catch{/* ignore invalid local preference */}},[]);useEffect(()=>{localStorage.setItem("projects.filters",JSON.stringify({archived,search,status:statusFilter,phase:phaseFilter}))},[archived,search,statusFilter,phaseFilter]);
 useEffect(()=>{const handler=()=>{setSelected(null);setEditingId(null);setForm(empty());setFormAttempted(false);setShowForm(true)};window.addEventListener("workspace:new",handler);return()=>window.removeEventListener("workspace:new",handler)},[]);
 useEffect(()=>{if(!selected)return;setRecentIds(current=>{const next=[selected.id,...current.filter(id=>id!==selected.id)].slice(0,8);localStorage.setItem("projects.recent",JSON.stringify(next));return next})},[selected]);
 const load=async()=>{try{const list=await invoke<Project[]>("list_projects",{includeArchived:archived});setProjects(list);const id=takeFocus("projects");const focused=list.find(v=>v.id===id);if(focused)setSelected(focused);}catch(e){setError(describeAppError(e));}}; useEffect(()=>{void load()},[archived]);
 const visible=useMemo(()=>projects.filter(p=>`${p.number} ${p.name} ${p.customer??""}`.toLowerCase().includes(search.toLowerCase())&&(statusFilter==="all"||p.status===statusFilter)&&(phaseFilter==="all"||p.phase===phaseFilter)).sort((a,b)=>Number(b.isPinned)-Number(a.isPinned)||(recentIds.indexOf(a.id)<0?99:recentIds.indexOf(a.id))-(recentIds.indexOf(b.id)<0?99:recentIds.indexOf(b.id))),[projects,search,statusFilter,phaseFilter,recentIds]);
 const change=(key:keyof Input,value:string)=>setForm(v=>({...v,[key]:value, ...(key==="phase"&&value!=="custom"?{customPhaseName:""}:{})}));
 const validationFields=()=>requiredFieldErrors([{key:"project-number",label:"Project number",value:form.number},{key:"project-name",label:"Project name",value:form.name},{key:"project-custom-phase",label:"Custom phase name",value:form.customPhaseName,required:form.phase==="custom"}]);
 const formErrors=formAttempted?validationFields():{};
 const validateForm=()=>{setFormAttempted(true);const errors=validationFields();const first=firstFieldError(errors);if(first){document.getElementById(first)?.focus();return false}return true};
 const create=async()=>{if(!validateForm())return;setCreating(true);setError("");try{const wasEditing=Boolean(editingId);const project=editingId?await invoke<Project>("update_project",{id:editingId,input:form}):await invoke<Project>("create_project",{input:form});setProjects(v=>editingId?v.map(p=>p.id===project.id?project:p):[project,...v]);setSelected(project);setForm(empty());setFormAttempted(false);setShowForm(false);setEditingId(null);onProjectsChanged?.();setMessage(wasEditing?`Updated ${project.number} — ${project.name}.`:`Created ${project.number} — ${project.name}. Folder structure is ready. Open its workspace to continue.`)}catch(e){setError(describeAppError(e))}finally{setCreating(false)}};
 const previewFolder=async()=>{if(!validateForm())return;try{const preview=await invoke<FolderPreview>("preview_project_folder",{input:form});setMessage(`Proposed folder: ${preview.projectPath}`);setError("")}catch(e){setError(describeAppError(e))}};
 const flag=async(id:string,arch?:boolean,pin?:boolean)=>{try{await invoke("set_project_flag",{id,archived:arch,pinned:pin});await load()}catch(e){setError(describeAppError(e))}};
 const closeMenu=(target:HTMLElement)=>{const menu=target.closest("details") as HTMLDetailsElement|null;if(menu)menu.open=false};
 const openPrimary=(project:Project)=>{if(project.archivedAtUtc){setSelected(project);return}setRecentIds(current=>{const next=[project.id,...current.filter(id=>id!==project.id)].slice(0,8);localStorage.setItem("projects.recent",JSON.stringify(next));return next});onOpenWorkspace?.(project)};
 const changeArchive=async(project:Project)=>{if(!project.archivedAtUtc&&!await confirmAction({title:"Archive this project?",description:<><p><strong>{project.number} — {project.name}</strong> will leave normal project views.</p><p>Its records and project files remain unchanged, and the project can be restored later.</p></>,confirmLabel:"Archive project",destructive:true}))return;void flag(project.id,!project.archivedAtUtc)};
 return <section className="projects-page" aria-labelledby="projects-title">{confirmationDialog}<div className="page-toolbar"><div><p className="eyebrow">Projects</p><h1 id="projects-title">Project workspaces</h1></div><button onClick={()=>{setEditingId(null);setForm(empty());setFormAttempted(false);setShowForm(v=>!v)}}>{showForm?"Close create":"New project"}</button></div>
 {showForm&&<form className="create-panel" noValidate onSubmit={event=>{event.preventDefault();void create()}}><h2>{editingId?"Edit project":"Create project"}</h2><p>{editingId?"Project metadata is updated without changing or renaming its existing folder.":"Start with the project identity. Review the exact folder path before creation; existing folders are never overwritten."}</p><div className="form-grid project-identity-fields"><Field id="project-number" label="Project number" value={form.number} onChange={v=>change("number",v)} required error={formErrors["project-number"]}/><Field id="project-name" label="Project name" value={form.name} onChange={v=>change("name",v)} required error={formErrors["project-name"]}/><Select label="Phase" value={form.phase} options={["preconstruction","engineering","submittals","procurement","construction","programming","startup","commissioning","closeout","custom"]} onChange={v=>change("phase",v)}/>{form.phase==="custom"&&<Field id="project-custom-phase" label="Custom phase name" value={form.customPhaseName} onChange={v=>change("customPhaseName",v)} required error={formErrors["project-custom-phase"]}/>}<Field label="Customer" value={form.customer} onChange={v=>change("customer",v)}/>{editingId&&<Select label="Status" value={form.status} options={["active","on_hold","completed","cancelled"]} onChange={v=>change("status",v)}/>}</div>{editingId&&<details className="optional-details"><summary>Additional project information</summary><div className="form-grid"><Field label="Location" value={form.location} onChange={v=>change("location",v)}/><Field label="General contractor" value={form.generalContractor} onChange={v=>change("generalContractor",v)}/><Field label="Engineer" value={form.engineer} onChange={v=>change("engineer",v)}/><Field label="Project manager" value={form.projectManager} onChange={v=>change("projectManager",v)}/><Field label="Superintendent" value={form.superintendent} onChange={v=>change("superintendent",v)}/><Field label="Start date" value={form.startDate} onChange={v=>change("startDate",v)} type="date"/><Field label="Target date" value={form.targetDate} onChange={v=>change("targetDate",v)} type="date"/><Field label="Description" value={form.description} onChange={v=>change("description",v)} multiline wide/><Field label="Important notes" value={form.importantNotes} onChange={v=>change("importantNotes",v)} multiline wide/></div></details>}<div className="actions">{!editingId&&<button type="button" className="secondary" onClick={()=>void previewFolder()} disabled={creating}>Preview folder</button>}<button type="submit" disabled={creating}>{creating?(editingId?"Saving…":"Creating…"):(editingId?"Save project":"Create project")}</button></div></form>}
 <div className="list-tools"><input aria-label="Search projects" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search number, name, customer"/><select aria-label="Filter by status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option>{["active","on_hold","completed","cancelled"].map(value=><option key={value} value={value}>{label(value)}</option>)}</select><select aria-label="Filter by phase" value={phaseFilter} onChange={e=>setPhaseFilter(e.target.value)}><option value="all">All phases</option>{["preconstruction","engineering","submittals","procurement","construction","programming","startup","commissioning","closeout","custom"].map(value=><option key={value} value={value}>{label(value)}</option>)}</select><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Include archived</label></div>
 {message&&<p className="status success">{message}</p>}{error&&<p className="status error" role="alert">{error}</p>}
 {selected&&<aside className="project-overview" aria-label="Project overview"><div><p className="eyebrow">Project overview</p><h2>{selected.number} — {selected.name}</h2><p>{label(selected.status)} · {selected.phase==="custom"?selected.customPhaseName:label(selected.phase)}</p><p className="saved-path">{selected.projectPath}</p></div><div className="actions">{!selected.archivedAtUtc&&<button onClick={()=>onOpenWorkspace?.(selected)}>Open workspace</button>}<button className="secondary" onClick={()=>void invoke("open_project_folder",{id:selected.id}).catch(e=>setError(describeAppError(e)))}>Open folder</button><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div></aside>}
 <div className="table-scroll projects-register"><table><thead><tr><th>Project</th><th>Status</th><th>Phase</th><th>Customer</th><th>Target</th><th aria-label="Actions"></th></tr></thead><tbody>{visible.map(p=><tr key={p.id} className={selected?.id===p.id?"selected-row":""} aria-selected={selected?.id===p.id} onDoubleClick={(event)=>{if(!(event.target as HTMLElement).closest("button,summary"))openPrimary(p)}}><td><button className="project-link project-primary" onClick={()=>openPrimary(p)} aria-label={`${p.archivedAtUtc?"Review archived project":"Open workspace"} ${p.number} — ${p.name}`}><strong>{p.number} — {p.name}</strong>{p.isPinned&&<span className="task-subline">Pinned</span>}</button></td><td>{label(p.status)}{p.archivedAtUtc&&<span className="task-subline">Archived</span>}</td><td>{p.phase==="custom"?p.customPhaseName:label(p.phase)}</td><td>{p.customer??"—"}</td><td>{p.targetDate??"—"}</td><td className="row-actions"><details className="row-menu"><summary aria-label={`More actions for ${p.number} — ${p.name}`}>More</summary><div className="row-menu-popover"><button type="button" onClick={(event)=>{setSelected(p);closeMenu(event.currentTarget)}}>View details</button><button type="button" onClick={(event)=>{setForm(fromProject(p));setFormAttempted(false);setEditingId(p.id);setShowForm(true);closeMenu(event.currentTarget)}}>Edit project</button><button type="button" onClick={(event)=>{closeMenu(event.currentTarget);void invoke("open_project_folder",{id:p.id}).catch(e=>setError(describeAppError(e)))}}>Open folder</button><button type="button" onClick={(event)=>{closeMenu(event.currentTarget);void flag(p.id,undefined,!p.isPinned)}}>{p.isPinned?"Unpin":"Pin"}</button><button type="button" className={p.archivedAtUtc?undefined:"destructive"} onClick={(event)=>{closeMenu(event.currentTarget);void changeArchive(p)}}>{p.archivedAtUtc?"Restore project":"Archive project"}</button></div></details></td></tr>)}{visible.length===0&&<tr><td colSpan={6} className="empty"><EmptyState title={projects.length?"No projects match these filters":"No project workspaces yet"} action={projects.length?<button type="button" className="secondary" onClick={()=>{setSearch("");setStatusFilter("all");setPhaseFilter("all")}}>Clear filters</button>:<button type="button" onClick={()=>{setEditingId(null);setForm(empty());setFormAttempted(false);setShowForm(true)}}>Create first project</button>}>{projects.length?"Change or clear the current filters to return to the full register.":"Create a project to establish its folder and begin tracking work. You can review the root location in Settings first."}</EmptyState>{!projects.length&&!archived&&onOpenSettings&&<button type="button" className="quiet" onClick={onOpenSettings}>Review project root in Settings</button>}</td></tr>}</tbody></table></div></section>;
}
function Field({id,label: text,value,onChange,required,type="text",multiline=false,wide=false,error}:{id?:string;label:string;value:string;onChange:(v:string)=>void;required?:boolean;type?:string;multiline?:boolean;wide?:boolean;error?:string}){const errorId=id?`${id}-error`:undefined;return <label className={wide?"wide-field":undefined} htmlFor={id}>{text}{required&&" *"}{multiline?<textarea id={id} required={required} value={value} onChange={e=>onChange(e.target.value)} aria-invalid={Boolean(error)} aria-describedby={error&&errorId?errorId:undefined}/>:<input id={id} required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} aria-invalid={Boolean(error)} aria-describedby={error&&errorId?errorId:undefined}/>} {id&&<FieldError id={errorId!}>{error}</FieldError>}</label>}; function Select({label: text,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label>{text}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{label(o)}</option>)}</select></label>}
