import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { describeAppError } from "./error";
import { takeFocus } from "./focus";

type Project = { id:string; number:string; name:string; status:string; phase:string; customPhaseName:string|null; customer:string|null; generalContractor:string|null; engineer:string|null; projectManager:string|null; superintendent:string|null; location:string|null; startDate:string|null; targetDate:string|null; description:string|null; importantNotes:string|null; projectPath:string; isPinned:boolean; archivedAtUtc:string|null };
type FolderPreview = { projectPath: string };
type Input = { number:string; name:string; status:string; phase:string; customPhaseName:string; customer:string; generalContractor:string; engineer:string; projectManager:string; superintendent:string; location:string; startDate:string; targetDate:string; description:string; importantNotes:string };
const empty = (): Input => ({ number:"",name:"",status:"active",phase:"engineering",customPhaseName:"",customer:"",generalContractor:"",engineer:"",projectManager:"",superintendent:"",location:"",startDate:"",targetDate:"",description:"",importantNotes:"" });
const fromProject = (p:Project):Input => ({ number:p.number,name:p.name,status:p.status,phase:p.phase,customPhaseName:p.customPhaseName??"",customer:p.customer??"",generalContractor:p.generalContractor??"",engineer:p.engineer??"",projectManager:p.projectManager??"",superintendent:p.superintendent??"",location:p.location??"",startDate:p.startDate??"",targetDate:p.targetDate??"",description:p.description??"",importantNotes:p.importantNotes??"" });
const label = (value:string) => ({active:"Active",on_hold:"On Hold",completed:"Completed",cancelled:"Cancelled",preconstruction:"Preconstruction",engineering:"Engineering",submittals:"Submittals",procurement:"Procurement",construction:"Construction",programming:"Programming",startup:"Startup",commissioning:"Commissioning",closeout:"Closeout",custom:"Custom"}[value] ?? value);
export function Projects({onOpenSettings}:{onOpenSettings?:()=>void}={}) {
 const [projects,setProjects]=useState<Project[]>([]); const [form,setForm]=useState<Input>(empty); const [creating,setCreating]=useState(false); const [showForm,setShowForm]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [archived,setArchived]=useState(false); const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState("all"); const [phaseFilter,setPhaseFilter]=useState("all"); const [selected,setSelected]=useState<Project|null>(null); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const [recentIds,setRecentIds]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem("projects.recent")??"[]") as string[]}catch{return[]}});
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem("projects.filters")??"null");if(v){setArchived(Boolean(v.archived));setSearch(v.search??"");setStatusFilter(v.status??"all");setPhaseFilter(v.phase??"all")}}catch{/* ignore invalid local preference */}},[]);useEffect(()=>{localStorage.setItem("projects.filters",JSON.stringify({archived,search,status:statusFilter,phase:phaseFilter}))},[archived,search,statusFilter,phaseFilter]);
 useEffect(()=>{const handler=()=>{setSelected(null);setEditingId(null);setForm(empty());setShowForm(true)};window.addEventListener("workspace:new",handler);return()=>window.removeEventListener("workspace:new",handler)},[]);
 useEffect(()=>{if(!selected)return;setRecentIds(current=>{const next=[selected.id,...current.filter(id=>id!==selected.id)].slice(0,8);localStorage.setItem("projects.recent",JSON.stringify(next));return next})},[selected]);
 const load=async()=>{try{const list=await invoke<Project[]>("list_projects",{includeArchived:archived});setProjects(list);const id=takeFocus("projects");const focused=list.find(v=>v.id===id);if(focused)setSelected(focused);}catch(e){setError(describeAppError(e));}}; useEffect(()=>{void load()},[archived]);
 const visible=useMemo(()=>projects.filter(p=>`${p.number} ${p.name} ${p.customer??""}`.toLowerCase().includes(search.toLowerCase())&&(statusFilter==="all"||p.status===statusFilter)&&(phaseFilter==="all"||p.phase===phaseFilter)).sort((a,b)=>Number(b.isPinned)-Number(a.isPinned)||(recentIds.indexOf(a.id)<0?99:recentIds.indexOf(a.id))-(recentIds.indexOf(b.id)<0?99:recentIds.indexOf(b.id))),[projects,search,statusFilter,phaseFilter,recentIds]);
 const change=(key:keyof Input,value:string)=>setForm(v=>({...v,[key]:value, ...(key==="phase"&&value!=="custom"?{customPhaseName:""}:{})}));
 const create=async()=>{setCreating(true);setError("");try{const project=editingId?await invoke<Project>("update_project",{id:editingId,input:form}):await invoke<Project>("create_project",{input:form});setProjects(v=>editingId?v.map(p=>p.id===project.id?project:p):[project,...v]);setSelected(project);setForm(empty());setShowForm(false);setEditingId(null);setMessage(editingId?`Updated ${project.number} — ${project.name}.`:`Created ${project.number} — ${project.name}. Folder structure is ready.`)}catch(e){setError(describeAppError(e))}finally{setCreating(false)}};
 const flag=async(id:string,arch?:boolean,pin?:boolean)=>{try{await invoke("set_project_flag",{id,archived:arch,pinned:pin});await load()}catch(e){setError(describeAppError(e))}};
 return <section className="projects-page" aria-labelledby="projects-title"><div className="page-toolbar"><div><p className="eyebrow">Projects</p><h1 id="projects-title">Project workspaces</h1></div><button onClick={()=>{setEditingId(null);setForm(empty());setShowForm(v=>!v)}}>{showForm?"Close create":"New project"}</button></div>
 {showForm&&<div className="create-panel"><h2>{editingId?"Edit project":"Create project"}</h2><p>{editingId?"Project metadata is updated without changing its existing folder.":"Review the exact folder path before creation. Existing folders are never overwritten."}</p><div className="form-grid"><Field label="Project number" value={form.number} onChange={v=>change("number",v)} required/><Field label="Project name" value={form.name} onChange={v=>change("name",v)} required/><Select label="Status" value={form.status} options={["active","on_hold","completed","cancelled"]} onChange={v=>change("status",v)}/><Select label="Phase" value={form.phase} options={["preconstruction","engineering","submittals","procurement","construction","programming","startup","commissioning","closeout","custom"]} onChange={v=>change("phase",v)}/>{form.phase==="custom"&&<Field label="Custom phase name" value={form.customPhaseName} onChange={v=>change("customPhaseName",v)} required/>}<Field label="Customer" value={form.customer} onChange={v=>change("customer",v)}/><Field label="Location" value={form.location} onChange={v=>change("location",v)}/></div><div className="actions">{!editingId&&<button className="secondary" onClick={()=>void invoke<FolderPreview>("preview_project_folder",{input:form}).then(p=>setMessage(`Proposed folder: ${p.projectPath}`)).catch(e=>setError(describeAppError(e)))} disabled={creating}>Preview folder</button>}<button onClick={()=>void create()} disabled={creating||!form.number.trim()||!form.name.trim()||(form.phase==="custom"&&!form.customPhaseName.trim())}>{creating?(editingId?"Saving…":"Creating…"):(editingId?"Save project":"Create project")}</button></div></div>}
 <div className="list-tools"><input aria-label="Search projects" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search number, name, customer"/><select aria-label="Filter by status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option>{["active","on_hold","completed","cancelled"].map(value=><option key={value} value={value}>{label(value)}</option>)}</select><select aria-label="Filter by phase" value={phaseFilter} onChange={e=>setPhaseFilter(e.target.value)}><option value="all">All phases</option>{["preconstruction","engineering","submittals","procurement","construction","programming","startup","commissioning","closeout","custom"].map(value=><option key={value} value={value}>{label(value)}</option>)}</select><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Include archived</label></div>
 {message&&<p className="status success">{message}</p>}{error&&<p className="status error" role="alert">{error}</p>}
 {selected&&<aside className="project-overview" aria-label="Project overview"><div><p className="eyebrow">Project overview</p><h2>{selected.number} — {selected.name}</h2><p>{label(selected.status)} · {selected.phase==="custom"?selected.customPhaseName:label(selected.phase)}</p><p className="saved-path">{selected.projectPath}</p></div><div className="actions"><button className="secondary" onClick={()=>void invoke("open_project_folder",{id:selected.id}).catch(e=>setError(describeAppError(e)))}>Open folder</button><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div></aside>}
 <table><thead><tr><th>Project</th><th>Status</th><th>Phase</th><th>Customer</th><th>Folder</th><th aria-label="Actions"></th></tr></thead><tbody>{visible.map(p=><tr key={p.id} onDoubleClick={()=>setSelected(p)}><td><button className="project-link" onClick={()=>setSelected(p)}><strong>{p.number}</strong><br/><span>{p.name}</span></button></td><td>{label(p.status)}</td><td>{p.phase==="custom"?p.customPhaseName:label(p.phase)}</td><td>{p.customer??"—"}</td><td>{p.archivedAtUtc?"Archived":"Active"}</td><td className="row-actions"><button className="quiet" onClick={()=>{setForm(fromProject(p));setEditingId(p.id);setShowForm(true)}}>Edit</button><button className="quiet" onClick={()=>void invoke("open_project_folder",{id:p.id}).catch(e=>setError(describeAppError(e)))}>Open folder</button><button className="quiet" onClick={()=>void flag(p.id,undefined,!p.isPinned)}>{p.isPinned?"Unpin":"Pin"}</button><button className="quiet" onClick={()=>{if(p.archivedAtUtc||confirm(`Archive ${p.number} — ${p.name}? It will leave normal project views but can be restored.`))void flag(p.id,!p.archivedAtUtc)}}>{p.archivedAtUtc?"Restore":"Archive"}</button></td></tr>)}{visible.length===0&&<tr><td colSpan={6} className="empty">No projects in this view. {!archived&&onOpenSettings&&<button type="button" className="quiet" onClick={onOpenSettings}>Open Settings to choose a project root</button>}</td></tr>}</tbody></table></section>;
}
function Field({label: text,value,onChange,required}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label>{text}{required&&" *"}<input value={value} onChange={e=>onChange(e.target.value)}/></label>}; function Select({label: text,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label>{text}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{label(o)}</option>)}</select></label>}
