import { useEffect, useMemo, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open, save as saveDialog } from "@tauri-apps/plugin-dialog";
import { describeAppError } from "./error";
import { takeFocus } from "./focus";
import { useProjectContext } from "./projectContext";
import { inheritedProjectId } from "./projectInheritance";
import { DetailPanel } from "./DetailPanel";
import { applyRfiLifecycleAction, rfiLifecycleAction, type RfiLifecycleStatus } from "./rfiLifecycle";
import { suggestRecordNumber } from "./numberSuggestions";
import { useConfirmation } from "./Feedback";
import { rfiPayload, type RfiFormInput } from "./rfiPayload";

type Project = { id: string; number: string; name: string };
type Task = { id: string; projectId: string; title: string };
type Rfi = { id: string; projectId: string; projectNumber: string; projectName: string; number: string; subject: string; question: string; recipient: string | null; status: string; createdDate: string; submittedDate: string | null; responseDueDate: string | null; responseReceivedDate: string | null; response: string | null; notes: string | null; rfiLocation: string | null; drawingNumber: string | null; costImpact: string | null; timeDelay: string | null; suggestedSolution: string | null; requestedBy: string | null; relatedTaskId: string | null };
type Attachment = { id: string; filePath: string; displayName: string };
type RfiInput = RfiFormInput;
const statuses = ["draft", "open", "response_received", "closed"];
const labels: Record<string, string> = { draft: "Draft", open: "Open", response_received: "Response Received", closed: "Closed" };
function today() { const date = new Date(); return date.getFullYear() + "-" + String(date.getMonth() + 1).padStart(2, "0") + "-" + String(date.getDate()).padStart(2, "0"); }
function blank(projectId = ""): RfiInput { return { projectId, number: "", subject: "", question: "", recipient: "", status: "draft", createdDate: today(), submittedDate: "", responseDueDate: "", responseReceivedDate: "", response: "", notes: "", rfiLocation: "", drawingNumber: "", costImpact: "", timeDelay: "", suggestedSolution: "", requestedBy: "", relatedTaskId: "" }; }
function fromRfi(rfi: Rfi): RfiInput { return { projectId: rfi.projectId, number: rfi.number, subject: rfi.subject, question: rfi.question, recipient: rfi.recipient ?? "", status: rfi.status, createdDate: rfi.createdDate, submittedDate: rfi.submittedDate ?? "", responseDueDate: rfi.responseDueDate ?? "", responseReceivedDate: rfi.responseReceivedDate ?? "", response: rfi.response ?? "", notes: rfi.notes ?? "", rfiLocation: rfi.rfiLocation ?? "", drawingNumber: rfi.drawingNumber ?? "", costImpact: rfi.costImpact ?? "", timeDelay: rfi.timeDelay ?? "", suggestedSolution: rfi.suggestedSolution ?? "", requestedBy: rfi.requestedBy ?? "", relatedTaskId: rfi.relatedTaskId ?? "" }; }

export function Rfis() {
  const { confirmAction, confirmationDialog } = useConfirmation();
  const projectContext = useProjectContext();
  const [rfis, setRfis] = useState<Rfi[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [tasks, setTasks] = useState<Task[]>([]);
  const [selected, setSelected] = useState<Rfi | null>(null); const [form, setForm] = useState<RfiInput>(()=>blank(inheritedProjectId(projectContext))); const [showCreate, setShowCreate] = useState(false); const [attachments, setAttachments] = useState<Attachment[]>([]);
  const [search, setSearch] = useState(""); const [projectFilter, setProjectFilter] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [working, setWorking] = useState(false);
  const returnFocusRef=useRef<HTMLElement|null>(null);
  useEffect(()=>{try{const v=JSON.parse(localStorage.getItem("rfis.filters")??"null");if(v){setSearch(v.search??"");setProjectFilter(v.project??"");setStatusFilter(v.status??"")}}catch{/* ignore invalid local preference */}},[]);useEffect(()=>{localStorage.setItem("rfis.filters",JSON.stringify({search,project:projectFilter,status:statusFilter}))},[search,projectFilter,statusFilter]);
  useEffect(()=>setProjectFilter(projectContext),[projectContext]);
  useEffect(()=>{if(showCreate&&!selected){const projectId=inheritedProjectId(projectContext);setForm(current=>({...current,projectId,number:current.number||(projectId?suggestRecordNumber(rfis.filter(rfi=>rfi.projectId===projectId).map(rfi=>rfi.number),"RFI"):""),relatedTaskId:""}))}},[projectContext,showCreate,selected,rfis]);
  useEffect(()=>{const handler=()=>{setSelected(null);setForm(blank(inheritedProjectId(projectContext)));setShowCreate(true)};window.addEventListener("workspace:new",handler);return()=>window.removeEventListener("workspace:new",handler)},[projectContext]);
  const load = async () => { try { const [rfiList, projectList, taskList] = await Promise.all([invoke<Rfi[]>("list_rfis"), invoke<Project[]>("list_projects", { includeArchived: false }), invoke<Task[]>("list_tasks")]); setRfis(rfiList); setProjects(projectList); setTasks(taskList); const id=takeFocus("rfis");const focused=rfiList.find(v=>v.id===id);if(focused){setSelected(focused);setForm(fromRfi(focused));} } catch (caught) { setError(describeAppError(caught)); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (selected) void invoke<Attachment[]>("list_rfi_attachments", { rfiId: selected.id }).then(setAttachments).catch((caught) => setError(describeAppError(caught))); else setAttachments([]); }, [selected]);
  const visible = useMemo(() => rfis.filter((rfi) => (!search.trim() || (rfi.number + " " + rfi.subject + " " + rfi.projectNumber + " " + rfi.projectName).toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())) && (!projectFilter || rfi.projectId === projectFilter) && (!statusFilter || rfi.status === statusFilter)), [rfis, search, projectFilter, statusFilter]);
  const projectTasks = tasks.filter((task) => task.projectId === form.projectId);
  const change = (key: keyof RfiInput, value: string) => setForm((current) => ({ ...current, [key]: value, ...(key === "projectId" ? { relatedTaskId: "",number:current.number||(value?suggestRecordNumber(rfis.filter(rfi=>rfi.projectId===value).map(rfi=>rfi.number),"RFI"):"") } : {}) }));
  async function save(createPdf: boolean, input: RfiInput = form, successMessage?: string) { setWorking(true); setError(""); const wasEditing=Boolean(selected); try { const payload=rfiPayload(input); const rfi = selected ? await invoke<Rfi>("update_rfi", { id: selected.id, input:payload }) : await invoke<Rfi>("create_rfi", { input:payload }); setSelected(rfi); setForm(fromRfi(rfi)); setShowCreate(false); let resultMessage=successMessage??(wasEditing ? "RFI updated." : "RFI created."); if(createPdf){ const defaultPath=await invoke<string>("get_rfi_pdf_default_path",{id:rfi.id}); const outputPath=await saveDialog({title:`Create PDF for ${rfi.number}`,defaultPath,filters:[{name:"PDF document",extensions:["pdf"]}]}); if(typeof outputPath==="string"){ const createdPath=await invoke<string>("export_rfi_pdf",{id:rfi.id,outputPath}); setAttachments(await invoke<Attachment[]>("list_rfi_attachments", { rfiId: rfi.id })); resultMessage=`RFI saved and PDF created: ${createdPath}`; } else { resultMessage="RFI saved. PDF creation was cancelled."; } } setMessage(resultMessage); await load(); } catch (caught) { setError(describeAppError(caught)); } finally { setWorking(false); } }
  function runLifecycle(nextStatus:RfiLifecycleStatus){const next=applyRfiLifecycleAction(form,nextStatus,today());const successMessage=nextStatus==="open"?"RFI submitted.":nextStatus==="response_received"?"Response recorded.":"RFI closed.";setForm(next);void save(false,next,successMessage)}
  async function addAttachment() { if (!selected) return; const selectedFile = await open({ multiple: false, directory: false, title: "Reference an existing RFI attachment" }); if (typeof selectedFile !== "string") return; setWorking(true); try { await invoke("add_rfi_attachment", { rfiId: selected.id, filePath: selectedFile }); setAttachments(await invoke<Attachment[]>("list_rfi_attachments", { rfiId: selected.id })); setMessage("Attachment reference added. The original file was not copied or moved."); } catch (caught) { setError(describeAppError(caught)); } finally { setWorking(false); } }
  async function removeAttachment(id: string, name: string) { if (!await confirmAction({ title: "Remove this attachment reference?", description: <><p><strong>{name}</strong> will no longer be linked to this RFI.</p><p>The original file will not be changed or deleted.</p></>, confirmLabel: "Remove reference", destructive: true })) return; setWorking(true); try { await invoke("remove_rfi_attachment", { id }); setAttachments((items) => items.filter((item) => item.id !== id)); setMessage("Attachment reference removed. The original file was not changed."); } catch (caught) { setError(describeAppError(caught)); } finally { setWorking(false); } }
  function beginCreate() { const projectId=inheritedProjectId(projectContext);setSelected(null); setForm({...blank(projectId),number:projectId?suggestRecordNumber(rfis.filter(rfi=>rfi.projectId===projectId).map(rfi=>rfi.number),"RFI"):""}); setShowCreate(true); setError(""); setMessage(""); }
  function choose(rfi: Rfi,trigger:HTMLElement) { returnFocusRef.current=trigger; setSelected(rfi); setForm(fromRfi(rfi)); setShowCreate(false); setError(""); }
  function closeDetail(){setSelected(null);setShowCreate(false)}
  return <section className="projects-page" aria-labelledby="rfis-title">{confirmationDialog}<div className="page-toolbar"><div><p className="eyebrow">RFIs</p><h1 id="rfis-title">Requests for information</h1></div><button onClick={(event)=>{returnFocusRef.current=event.currentTarget;beginCreate()}} aria-expanded={showCreate} aria-controls="rfi-detail-panel">New RFI</button></div>
    <div className="list-tools task-filters" aria-label="RFI filters"><label className="search-filter">Search<input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Number, subject, or project" /></label><label>Project<select value={projectFilter} onChange={(event) => setProjectFilter(event.target.value)}><option value="">All projects</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.number} — {project.name}</option>)}</select></label><label>Status<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{labels[status]}</option>)}</select></label>{(search || projectFilter || statusFilter) && <button type="button" className="quiet clear-filters" onClick={() => { setSearch(""); setProjectFilter(""); setStatusFilter(""); }}>Clear filters</button>}</div>
    {message && <p className="status success" role="status">{message}</p>}{error && <p className="status error" role="alert">{error}</p>}
    <div className={`rfi-layout${showCreate||selected?" has-detail":" register-only"}`}><div className="table-scroll"><table><thead><tr><th>RFI</th><th>Project</th><th>Recipient</th><th>Response due</th><th>Status</th></tr></thead><tbody>{visible.map((rfi) => <tr key={rfi.id} className={selected?.id === rfi.id ? "selected-row" : ""} aria-selected={selected?.id===rfi.id}><td><button className="project-link" onClick={(event) => choose(rfi,event.currentTarget)} aria-expanded={selected?.id===rfi.id} aria-controls="rfi-detail-panel"><strong>{rfi.number}</strong><br /><span>{rfi.subject}</span></button></td><td>{rfi.projectNumber} — {rfi.projectName}</td><td>{rfi.recipient ?? "—"}</td><td>{rfi.responseDueDate ?? "—"}</td><td>{labels[rfi.status]}</td></tr>)}{!visible.length && <tr><td className="empty" colSpan={5}>No RFIs match this view. Create an RFI when a project needs a documented answer.</td></tr>}</tbody></table></div>
      <DetailPanel open={Boolean(showCreate||selected)} id="rfi-detail-panel" className="rfi-detail" ariaLabel={selected ? "Edit RFI" : "Create RFI"} eyebrow={selected ? "RFI detail" : "New RFI"} title={selected ? selected.number : "Create RFI"} onClose={closeDetail} returnFocusRef={returnFocusRef}><RfiForm form={form} projects={projects} tasks={projectTasks} change={change} onSave={(createPdf) => void save(createPdf)} onLifecycle={selected?runLifecycle:undefined} working={working} />
        {selected && <section className="attachment-section" aria-labelledby="attachments-title"><div className="detail-heading"><div><h3 id="attachments-title">Attachment references</h3><p>References only; files stay where they are.</p></div><button type="button" className="secondary" onClick={() => void addAttachment()} disabled={working}>Reference file…</button></div>{attachments.length ? <ul className="attachment-list">{attachments.map((attachment) => <li key={attachment.id}><span><strong>{attachment.displayName}</strong><small>{attachment.filePath}</small></span><span className="attachment-actions"><button type="button" className="quiet" onClick={() => void invoke("show_rfi_attachment_in_explorer", { id: attachment.id }).catch((caught) => setError(describeAppError(caught)))} disabled={working}>Show in Explorer</button><button type="button" className="quiet" onClick={() => void removeAttachment(attachment.id,attachment.displayName)} disabled={working}>Remove reference</button></span></li>)}</ul> : <p className="empty-state">No attachment references. Add one only when you want this RFI linked to an existing file.</p>}</section>}
      </DetailPanel></div>
  </section>;
}

function RfiForm({ form, projects, tasks, change, onSave, onLifecycle, working }: { form: RfiInput; projects: Project[]; tasks: Task[]; change: (key: keyof RfiInput, value: string) => void; onSave: (createPdf: boolean) => void; onLifecycle?: (nextStatus:RfiLifecycleStatus)=>void; working: boolean }) {
  const responseRequired = ["response_received", "closed"].includes(form.status);
  const lifecycleAction=onLifecycle?rfiLifecycleAction(form):null;
  return <form className="detail-form" onSubmit={(event) => { event.preventDefault(); onSave(true); }}>
    <div className="form-grid"><label>Project<select value={form.projectId} onChange={(event) => change("projectId", event.target.value)} required><option value="">Choose project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.number} — {project.name}</option>)}</select></label><label>RFI number <span className="optional">(suggested, editable)</span><input value={form.number} onChange={(event) => change("number", event.target.value)} required /></label><label className="wide-field">Subject<input value={form.subject} onChange={(event) => change("subject", event.target.value)} required /></label><label className="wide-field">Question<textarea value={form.question} onChange={(event) => change("question", event.target.value)} required /></label><label>Recipient <span className="optional">(required when Open)</span><input value={form.recipient} onChange={(event) => change("recipient", event.target.value)} required={form.status!=="draft"} /></label><label>Status<select value={form.status} onChange={(event) => change("status", event.target.value)}>{statuses.map((status) => <option key={status} value={status}>{labels[status]}</option>)}</select></label></div>
    {responseRequired ? <div className="lifecycle-guidance" role="note">Response Received and Closed RFIs require both a response and the date it was received.</div> : null}
    <details className="optional-details"><summary>PDF template details</summary><div className="form-grid"><label>RFI location <span className="optional">(optional)</span><input value={form.rfiLocation} onChange={(event) => change("rfiLocation", event.target.value)} /></label><label>Drawing number <span className="optional">(optional)</span><input value={form.drawingNumber} onChange={(event) => change("drawingNumber", event.target.value)} /></label><label>Cost impact <span className="optional">(optional)</span><input value={form.costImpact} onChange={(event) => change("costImpact", event.target.value)} placeholder="None anticipated" /></label><label>Time delay <span className="optional">(optional)</span><input value={form.timeDelay} onChange={(event) => change("timeDelay", event.target.value)} placeholder="None anticipated" /></label><label className="wide-field">Suggested solution <span className="optional">(optional)</span><textarea value={form.suggestedSolution} onChange={(event) => change("suggestedSolution", event.target.value)} /></label><label className="wide-field">Requested by <span className="optional">(optional)</span><input value={form.requestedBy} onChange={(event) => change("requestedBy", event.target.value)} /></label></div></details>
    <details className="optional-details" open={form.status==="open"||responseRequired}><summary>Dates, response, and related work</summary><div className="form-grid"><label>Created date<input type="date" value={form.createdDate} onChange={(event) => change("createdDate", event.target.value)} required /></label><label>Submitted date <span className="optional">(optional)</span><input type="date" value={form.submittedDate} onChange={(event) => change("submittedDate", event.target.value)} /></label><label>Response due <span className="optional">(optional)</span><input type="date" value={form.responseDueDate} onChange={(event) => change("responseDueDate", event.target.value)} /></label><label>Response received {responseRequired ? "*" : <span className="optional">(optional)</span>}<input type="date" value={form.responseReceivedDate} onChange={(event) => change("responseReceivedDate", event.target.value)} required={responseRequired} /></label><label>Related task <span className="optional">(optional)</span><select value={form.relatedTaskId} onChange={(event) => change("relatedTaskId", event.target.value)}><option value="">No related task</option>{tasks.map((task) => <option key={task.id} value={task.id}>{task.title}</option>)}</select></label><label className="wide-field">Response {responseRequired ? "*" : <span className="optional">(optional)</span>}<textarea value={form.response} onChange={(event) => change("response", event.target.value)} required={responseRequired} /></label><label className="wide-field">Notes <span className="optional">(optional)</span><textarea value={form.notes} onChange={(event) => change("notes", event.target.value)} /></label></div></details>
    {lifecycleAction&&<section className="lifecycle-action" aria-label="RFI lifecycle action"><div><strong>Next step: {lifecycleAction.label}</strong><p>{lifecycleAction.disabledReason??"Saves the current edits and advances this RFI in one update."}</p></div><button type="button" onClick={()=>onLifecycle?.(lifecycleAction.nextStatus)} disabled={working||Boolean(lifecycleAction.disabledReason)}>{lifecycleAction.label}</button></section>}
    <div className="actions"><button type="button" className="secondary" onClick={() => onSave(false)} disabled={working || !form.projectId || !form.number.trim() || !form.subject.trim() || !form.question.trim() || (form.status!=="draft"&&!form.recipient.trim()) || (responseRequired&&(!form.response.trim()||!form.responseReceivedDate))}>Save only</button><button type="submit" disabled={working || !form.projectId || !form.number.trim() || !form.subject.trim() || !form.question.trim() || (form.status!=="draft"&&!form.recipient.trim()) || (responseRequired&&(!form.response.trim()||!form.responseReceivedDate))}>{working ? "Saving…" : "Save and create PDF"}</button></div>
  </form>;
}
