import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";
import { describeAppError } from "./error";
import { takeFocus } from "./focus";
import { useProjectContext } from "./projectContext";
import { inheritedProjectId } from "./projectInheritance";
import { applySubmittalLifecycleAction, submittalLifecycleAction, type SubmittalDisposition, type SubmittalLifecycleStatus } from "./submittalLifecycle";
import { suggestRecordNumber } from "./numberSuggestions";
import { useConfirmation } from "./Feedback";

type Project={id:string;number:string;name:string}; type Task={id:string;projectId:string;title:string}; type Attachment={id:string;filePath:string;displayName:string};
type Submittal={id:string;projectId:string;projectNumber:string;projectName:string;parentSubmittalId:string|null;number:string;name:string;package:string|null;revision:string|null;recipient:string|null;status:string;disposition:string|null;createdDate:string;submittedDate:string|null;responseDate:string|null;resubmissionRequired:boolean;notes:string|null;relatedTaskId:string|null};
type Input={projectId:string;parentSubmittalId:string;number:string;name:string;package:string;revision:string;recipient:string;status:string;createdDate:string;submittedDate:string;responseDate:string;resubmissionRequired:boolean;notes:string;relatedTaskId:string};
const statuses=["draft","preparing","submitted","under_review","approved","approved_as_noted","revise_and_resubmit","rejected","closed"];
const labels:Record<string,string>={draft:"Draft",preparing:"Preparing",submitted:"Submitted",under_review:"Under Review",approved:"Approved",approved_as_noted:"Approved As Noted",revise_and_resubmit:"Revise & Resubmit",rejected:"Rejected",closed:"Closed"};
const today=()=>{const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`};
const blank=(projectId=""):Input=>({projectId,parentSubmittalId:"",number:"",name:"",package:"",revision:"",recipient:"",status:"draft",createdDate:today(),submittedDate:"",responseDate:"",resubmissionRequired:false,notes:"",relatedTaskId:""});
const from=(v:Submittal):Input=>({projectId:v.projectId,parentSubmittalId:v.parentSubmittalId??"",number:v.number,name:v.name,package:v.package??"",revision:v.revision??"",recipient:v.recipient??"",status:v.status,createdDate:v.createdDate,submittedDate:v.submittedDate??"",responseDate:v.responseDate??"",resubmissionRequired:v.resubmissionRequired,notes:v.notes??"",relatedTaskId:v.relatedTaskId??""});
const payload=(v:Input)=>({...v,parentSubmittalId:v.parentSubmittalId||null,package:v.package||null,revision:v.revision||null,recipient:v.recipient||null,submittedDate:v.submittedDate||null,responseDate:v.responseDate||null,notes:v.notes||null,relatedTaskId:v.relatedTaskId||null});
const isDisposition=(status:string)=>["approved","approved_as_noted","revise_and_resubmit","rejected","closed"].includes(status);

export function Submittals(){
 const{confirmAction,confirmationDialog}=useConfirmation();
 const projectContext=useProjectContext();
 const [items,setItems]=useState<Submittal[]>([]),[projects,setProjects]=useState<Project[]>([]),[tasks,setTasks]=useState<Task[]>([]),[selected,setSelected]=useState<Submittal|null>(null),[form,setForm]=useState<Input>(()=>blank(inheritedProjectId(projectContext))),[showCreate,setShowCreate]=useState(false),[attachments,setAttachments]=useState<Attachment[]>([]),[search,setSearch]=useState(""),[projectFilter,setProjectFilter]=useState(""),[statusFilter,setStatusFilter]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[working,setWorking]=useState(false),[disposition,setDisposition]=useState<SubmittalDisposition>("approved");
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem("submittals.filters")??"null");if(v){setSearch(v.search??"");setProjectFilter(v.project??"");setStatusFilter(v.status??"")}}catch{/* ignore invalid local preference */}},[]); useEffect(()=>{localStorage.setItem("submittals.filters",JSON.stringify({search,project:projectFilter,status:statusFilter}))},[search,projectFilter,statusFilter]);
 useEffect(()=>setProjectFilter(projectContext),[projectContext]); useEffect(()=>{if(showCreate&&!selected&&!form.parentSubmittalId){const projectId=inheritedProjectId(projectContext);setForm(current=>({...current,projectId,number:current.number||(projectId?suggestRecordNumber(items.filter(item=>item.projectId===projectId).map(item=>item.number),"SUB"):"")}))}},[showCreate,selected,projectContext,items,form.parentSubmittalId]);
 useEffect(()=>{const handler=()=>{setSelected(null);setForm(blank(inheritedProjectId(projectContext)));setShowCreate(true)};window.addEventListener("workspace:new",handler);return()=>window.removeEventListener("workspace:new",handler)},[projectContext]);
 useEffect(()=>{if(!items.length)return;const id=takeFocus("submittals");const focused=items.find(v=>v.id===id);if(focused){setSelected(focused);setForm(from(focused));}},[items]);
 const load=async()=>{try{const [a,b,c]=await Promise.all([invoke<Submittal[]>("list_submittals"),invoke<Project[]>("list_projects",{includeArchived:false}),invoke<Task[]>("list_tasks")]);setItems(a);setProjects(b);setTasks(c)}catch(e){setError(describeAppError(e))}}; useEffect(()=>{void load()},[]);
 useEffect(()=>{if(selected)void invoke<Attachment[]>("list_submittal_attachments",{submittalId:selected.id}).then(setAttachments).catch(e=>setError(describeAppError(e)));else setAttachments([])},[selected]);
 const visible=useMemo(()=>items.filter(v=>(!search.trim()||(v.number+" "+v.name+" "+v.projectNumber+" "+v.projectName).toLowerCase().includes(search.trim().toLowerCase()))&&(!projectFilter||v.projectId===projectFilter)&&(!statusFilter||v.status===statusFilter)),[items,search,projectFilter,statusFilter]);
 const change=(key:keyof Input,value:string|boolean)=>setForm(current=>({...current,[key]:value,...(key==="projectId"&&typeof value==="string"?{relatedTaskId:"",number:current.number||(value?suggestRecordNumber(items.filter(item=>item.projectId===value).map(item=>item.number),"SUB"):"")}:{})})); const projectTasks=tasks.filter(v=>v.projectId===form.projectId); const lifecycleAction=selected?submittalLifecycleAction(form,disposition):null;
 async function save(input:Input=form,successMessage?:string){setWorking(true);setError("");try{const saved=selected?await invoke<Submittal>("update_submittal",{id:selected.id,input:payload(input)}):await invoke<Submittal>("create_submittal",{input:payload(input)});setSelected(saved);setForm(from(saved));setShowCreate(false);setMessage(successMessage??(selected?"Submittal updated.":"Submittal created."));await load()}catch(e){setError(describeAppError(e))}finally{setWorking(false)}}
 function choose(item:Submittal){setSelected(item);setForm(from(item));setDisposition("approved");setShowCreate(false);setError("")}
 function revision(){if(!selected)return;setSelected(null);setForm({...blank(selected.projectId),parentSubmittalId:selected.id,number:selected.number,name:selected.name,package:selected.package??"",relatedTaskId:selected.relatedTaskId??"",status:"preparing"});setShowCreate(true);setMessage("Enter the new revision before saving.")}
 function runLifecycle(nextStatus:SubmittalLifecycleStatus){const next=applySubmittalLifecycleAction(form,nextStatus,today());const success=nextStatus==="submitted"?"Submittal submitted.":nextStatus==="closed"?"Submittal closed.":"Disposition recorded.";setForm(next);void save(next,success)}
 async function attach(){if(!selected)return;const path=await open({multiple:false,directory:false,title:"Reference an existing submittal attachment"});if(typeof path!=="string")return;try{await invoke("add_submittal_attachment",{submittalId:selected.id,filePath:path});setAttachments(await invoke<Attachment[]>("list_submittal_attachments",{submittalId:selected.id}));setMessage("Attachment reference added. The original file was not copied or moved.")}catch(e){setError(describeAppError(e))}}
 async function removeAttachment(attachment:Attachment){if(!await confirmAction({title:"Remove this attachment reference?",description:<><p><strong>{attachment.displayName}</strong> will no longer be linked to this submittal.</p><p>The original file will not be changed or deleted.</p></>,confirmLabel:"Remove reference",destructive:true}))return;try{await invoke("remove_submittal_attachment",{id:attachment.id});setAttachments(current=>current.filter(item=>item.id!==attachment.id));setMessage("Attachment reference removed. The original file was not changed.")}catch(e){setError(describeAppError(e))}}
 function beginCreate(){const projectId=inheritedProjectId(projectContext);setSelected(null);setForm({...blank(projectId),number:projectId?suggestRecordNumber(items.filter(item=>item.projectId===projectId).map(item=>item.number),"SUB"):""});setShowCreate(true);setError("")}
 return <section className="projects-page" aria-labelledby="submittals-title">{confirmationDialog}
  <div className="page-toolbar"><div><p className="eyebrow">Submittals</p><h1 id="submittals-title">Submittal register</h1></div><button onClick={beginCreate}>New submittal</button></div>
  <div className="list-tools task-filters" aria-label="Submittal filters"><label className="search-filter">Search<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Number, name, or project"/></label><label>Project<select value={projectFilter} onChange={e=>setProjectFilter(e.target.value)}><option value="">All projects</option>{projects.map(v=><option key={v.id} value={v.id}>{v.number} — {v.name}</option>)}</select></label><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{statuses.map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label>{(search||projectFilter||statusFilter)&&<button className="quiet clear-filters" onClick={()=>{setSearch("");setProjectFilter("");setStatusFilter("")}}>Clear filters</button>}</div>
  {message&&<p className="status success" role="status">{message}</p>}{error&&<p className="status error" role="alert">{error}</p>}
  <div className={`rfi-layout${selected||showCreate?" has-detail":" register-only"}`}><div className="table-scroll"><table><thead><tr><th>Submittal</th><th>Project</th><th>Recipient</th><th>Submitted</th><th>Status</th></tr></thead><tbody>{visible.map(v=><tr key={v.id} className={selected?.id===v.id?"selected-row":""} aria-selected={selected?.id===v.id}><td><button className="project-link" onClick={()=>choose(v)}><strong>{v.number}{v.revision?` · Rev ${v.revision}`:""}</strong><br/><span>{v.name}</span></button></td><td>{v.projectNumber} — {v.projectName}</td><td>{v.recipient??"—"}</td><td>{v.submittedDate??"—"}</td><td>{labels[v.status]}</td></tr>)}{!visible.length&&<tr><td colSpan={5} className="empty">No submittals match this view. Create one when a project package needs documented review.</td></tr>}</tbody></table></div>
   {(selected||showCreate)&&<aside className="rfi-detail" aria-label={selected?"Edit submittal":"Create submittal"}><div className="detail-heading"><div><p className="eyebrow">{selected?"Submittal detail":"New submittal"}</p><h2>{selected?selected.number:"Create submittal"}</h2></div><button className="quiet" onClick={()=>{setSelected(null);setShowCreate(false)}}>Close</button></div>
    <form className="detail-form" onSubmit={e=>{e.preventDefault();void save()}}><div className="form-grid"><label>Project<select required value={form.projectId} onChange={e=>change("projectId",e.target.value)}><option value="">Choose project</option>{projects.map(v=><option key={v.id} value={v.id}>{v.number} — {v.name}</option>)}</select></label><label>Submittal number <span className="optional">(suggested, editable)</span><input required value={form.number} onChange={e=>change("number",e.target.value)}/></label><label className="wide-field">Name<input required value={form.name} onChange={e=>change("name",e.target.value)}/></label><label>Recipient <span className="optional">(required when Submitted)</span><input value={form.recipient} onChange={e=>change("recipient",e.target.value)} required={!['draft','preparing'].includes(form.status)}/></label><label>Status<select value={form.status} onChange={e=>change("status",e.target.value)}>{statuses.map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label></div>
     {isDisposition(form.status)&&<div className="lifecycle-guidance" role="note">A disposition requires a response date. Revise &amp; Resubmit also records whether another revision is required.</div>}
     <details className="optional-details" open={!['draft','preparing'].includes(form.status)}><summary>Package, dates, and related work</summary><div className="form-grid"><label>Package <span className="optional">(optional)</span><input value={form.package} onChange={e=>change("package",e.target.value)}/></label><label>Revision <span className="optional">(optional)</span><input value={form.revision} onChange={e=>change("revision",e.target.value)}/></label><label>Created date<input required type="date" value={form.createdDate} onChange={e=>change("createdDate",e.target.value)}/></label><label>Submitted date <span className="optional">(optional)</span><input type="date" value={form.submittedDate} onChange={e=>change("submittedDate",e.target.value)}/></label><label>Response date <span className="optional">(required for disposition)</span><input type="date" value={form.responseDate} onChange={e=>change("responseDate",e.target.value)} required={isDisposition(form.status)}/></label><label>Related task <span className="optional">(optional)</span><select value={form.relatedTaskId} onChange={e=>change("relatedTaskId",e.target.value)}><option value="">No related task</option>{projectTasks.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label>{["revise_and_resubmit","closed"].includes(form.status)&&<label className="checkbox-field"><input type="checkbox" checked={form.resubmissionRequired} onChange={e=>change("resubmissionRequired",e.target.checked)}/> Resubmission required</label>}<label className="wide-field">Notes <span className="optional">(optional)</span><textarea value={form.notes} onChange={e=>change("notes",e.target.value)}/></label></div></details>
     {lifecycleAction&&<section className="lifecycle-action" aria-label="Submittal lifecycle action"><div><strong>Next step: {lifecycleAction.label}</strong><p>{lifecycleAction.disabledReason??(lifecycleAction.kind==="revision"?"Starts a new revision linked to this submittal.":"Saves current edits and advances this submittal in one update.")}</p>{["submitted","under_review"].includes(form.status)&&<label className="lifecycle-choice">Disposition<select value={disposition} onChange={e=>setDisposition(e.target.value as SubmittalDisposition)}><option value="approved">Approved</option><option value="approved_as_noted">Approved As Noted</option><option value="revise_and_resubmit">Revise &amp; Resubmit</option><option value="rejected">Rejected</option></select></label>}</div><button type="button" onClick={()=>lifecycleAction.kind==="revision"?revision():lifecycleAction.nextStatus&&runLifecycle(lifecycleAction.nextStatus)} disabled={working||Boolean(lifecycleAction.disabledReason)}>{lifecycleAction.label}</button></section>}
     <div className="actions"><button type="submit" disabled={working||!form.projectId||!form.number.trim()||!form.name.trim()||(!['draft','preparing'].includes(form.status)&&!form.recipient.trim())||(isDisposition(form.status)&&!form.responseDate)}>{working?"Saving…":"Save submittal"}</button></div></form>
    {selected&&<section className="attachment-section"><div className="detail-heading"><div><h3>Attachment references</h3><p>References only; files stay where they are.</p></div><button className="secondary" type="button" onClick={()=>void attach()}>Reference file…</button></div>{attachments.length?<ul className="attachment-list">{attachments.map(v=><li key={v.id}><span><strong>{v.displayName}</strong><small>{v.filePath}</small></span><button className="quiet" type="button" onClick={()=>void removeAttachment(v)}>Remove reference</button></li>)}</ul>:<p className="empty-state">No attachment references.</p>}</section>}
   </aside>}
  </div>
 </section>
}
